print("Hello World!")
mylist=[1,2,3,4,5,6]
print(mylist)
mylist.append(7)
print(mylist)
mylist.insert(2,10)
mylist.remove(2)
print(mylist)
mylist.sort()
print(mylist)
mylist.reverse()
print(mylist)
mylist.pop()
print(mylist)
print("Last Element",mylist[-1])